import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AlertTriangle, Download } from "lucide-react";
import { buildPayrollSummary, computeOvertimeMap } from "@/lib/overtimeUtils";

const FREQ_LABELS = {
  "semi-monthly": "Semi-Monthly",
  "weekly": "Weekly",
  "bi-weekly": "Bi-Weekly",
  "monthly": "Monthly",
  "custom": "Custom",
};

function fmt(h) {
  if (!h && h !== 0) return "—";
  return `${Math.round(h * 100) / 100}h`;
}

export default function PayrollPreviewModal({ open, onClose, timecards, period, frequency, user, agencyName, onExportCSV, onExportPDF, params }) {
  if (!period) return null;

  const otMap = computeOvertimeMap(timecards);
  const summary = buildPayrollSummary(timecards, otMap);

  const totalHours = summary.reduce((s, e) => s + e.totalHours, 0);
  const totalOT = summary.reduce((s, e) => s + e.totalOT, 0);
  const totalEntries = summary.reduce((s, e) => s + e.entries.length, 0);

  const today = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            <span>Payroll Preview</span>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={() => onExportCSV?.(params)} className="gap-1 text-xs">
                <Download className="w-3.5 h-3.5" /> CSV
              </Button>
              <Button size="sm" variant="outline" onClick={() => onExportPDF?.(params)} className="gap-1 text-xs">
                <Download className="w-3.5 h-3.5" /> PDF
              </Button>
            </div>
          </DialogTitle>
        </DialogHeader>

        {/* Header Section */}
        <div className="bg-muted/40 rounded-lg p-4 mb-4 text-sm">
          <div className="font-bold text-base mb-2">{agencyName || "CareFlow Ops"}</div>
          <div className="grid grid-cols-2 gap-x-8 gap-y-1 text-muted-foreground">
            <div><span className="font-medium text-foreground">Pay Period:</span> {period.label}</div>
            <div><span className="font-medium text-foreground">Frequency:</span> {FREQ_LABELS[frequency] || frequency}</div>
            <div><span className="font-medium text-foreground">Generated On:</span> {today}</div>
            <div><span className="font-medium text-foreground">Generated By:</span> {user?.full_name || user?.email || "—"}</div>
          </div>
        </div>

        {/* Per-Employee Cards */}
        <div className="space-y-6">
          {summary.length === 0 && (
            <div className="text-center text-muted-foreground py-8">No timecards found for the selected criteria.</div>
          )}
          {summary.map(emp => (
            <div key={emp.staff_id} className={`border rounded-lg overflow-hidden ${emp.hasOT ? "border-orange-300" : "border-border"}`}>
              <div className={`flex items-center justify-between px-4 py-3 ${emp.hasOT ? "bg-orange-50" : "bg-muted/30"}`}>
                <div className="font-semibold text-sm">{emp.staff_name}</div>
                <div className="flex items-center gap-3">
                  {emp.hasOT && (
                    <Badge className="bg-orange-500 text-white gap-1 text-xs">
                      <AlertTriangle className="w-3 h-3" /> OT Detected
                    </Badge>
                  )}
                  <span className="text-sm text-muted-foreground">
                    Total: <span className="font-semibold text-foreground">{fmt(emp.totalHours)}</span>
                    {emp.totalOT > 0 && <span className="text-orange-600 ml-2">({fmt(emp.totalOT)} OT)</span>}
                  </span>
                </div>
              </div>
              <Table>
                <TableHeader>
                  <TableRow className="text-xs">
                    <TableHead>Date</TableHead>
                    <TableHead>Clock In</TableHead>
                    <TableHead>Clock Out</TableHead>
                    <TableHead>Hours</TableHead>
                    <TableHead>Regular</TableHead>
                    <TableHead>OT</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {emp.entries.sort((a, b) => a.date.localeCompare(b.date)).map(e => (
                    <TableRow key={e.id} className="text-xs">
                      <TableCell>{e.date}</TableCell>
                      <TableCell>{e.clock_in}</TableCell>
                      <TableCell>{e.clock_out || "—"}</TableCell>
                      <TableCell className="font-medium">
                        {fmt(e.total_hours)}
                        {e.isOT && <span className="ml-1 text-orange-600 font-bold">OT</span>}
                      </TableCell>
                      <TableCell>{fmt(e.tcRegular)}</TableCell>
                      <TableCell className={e.tcOT > 0 ? "text-orange-600 font-semibold" : ""}>{e.tcOT > 0 ? fmt(e.tcOT) : "—"}</TableCell>
                      <TableCell>
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                          e.status === "Approved" ? "bg-accent/10 text-accent"
                          : e.status === "Rejected" ? "bg-destructive/10 text-destructive"
                          : "bg-amber-500/10 text-amber-600"
                        }`}>{e.status}</span>
                      </TableCell>
                    </TableRow>
                  ))}
                  <TableRow className="bg-muted/30 font-semibold text-xs">
                    <TableCell colSpan={3} className="text-right">Subtotal</TableCell>
                    <TableCell>{fmt(emp.totalHours)}</TableCell>
                    <TableCell>{fmt(emp.totalRegular)}</TableCell>
                    <TableCell className={emp.totalOT > 0 ? "text-orange-600" : ""}>{emp.totalOT > 0 ? fmt(emp.totalOT) : "—"}</TableCell>
                    <TableCell></TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          ))}
        </div>

        {/* Footer Summary */}
        {summary.length > 0 && (
          <div className="mt-4 bg-muted/40 rounded-lg p-4 text-sm grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="text-center">
              <div className="text-xl font-bold">{summary.length}</div>
              <div className="text-xs text-muted-foreground">Employees</div>
            </div>
            <div className="text-center">
              <div className="text-xl font-bold">{totalEntries}</div>
              <div className="text-xs text-muted-foreground">Total Entries</div>
            </div>
            <div className="text-center">
              <div className="text-xl font-bold">{fmt(totalHours)}</div>
              <div className="text-xs text-muted-foreground">Total Hours</div>
            </div>
            <div className="text-center">
              <div className={`text-xl font-bold ${totalOT > 0 ? "text-orange-600" : ""}`}>{fmt(totalOT)}</div>
              <div className="text-xs text-muted-foreground">Total OT Hours</div>
            </div>
          </div>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}