import { buildPayrollSummary, computeOvertimeMap } from "@/lib/overtimeUtils";

function fmt(h) {
  if (!h && h !== 0) return "";
  return `${Math.round(h * 100) / 100}`;
}

function tsFilename(start, end) {
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  return `Payroll_${start}_${end}_exported_${ts}`;
}

export function exportCSV(timecards, period) {
  const otMap = computeOvertimeMap(timecards);
  const summary = buildPayrollSummary(timecards, otMap);

  const rows = [];
  rows.push(["Employee Name", "Date", "Clock In", "Clock Out", "Hours", "Week", "Regular Hours", "Overtime Hours", "Status", "Pay Period", "Locked"]);

  for (const emp of summary) {
    const sorted = [...emp.entries].sort((a, b) => a.date.localeCompare(b.date));
    for (const e of sorted) {
      rows.push([
        emp.staff_name,
        e.date,
        e.clock_in,
        e.clock_out || "",
        fmt(e.total_hours),
        e.weekLabel || "",
        fmt(e.tcRegular),
        fmt(e.tcOT),
        e.status,
        period.label,
        e.locked ? "Yes" : "No",
      ]);
    }
    // Subtotal row per employee
    rows.push([
      `${emp.staff_name} TOTAL`, "", "", "",
      fmt(emp.totalHours), "",
      fmt(emp.totalRegular),
      fmt(emp.totalOT),
      "", "", ""
    ]);
    rows.push(["", "", "", "", "", "", "", "", "", "", ""]);
  }

  const csv = rows.map(r => r.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${tsFilename(period.start, period.end)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportPDF(timecards, period, frequency, user, agencyName) {
  const otMap = computeOvertimeMap(timecards);
  const summary = buildPayrollSummary(timecards, otMap);
  const totalHours = summary.reduce((s, e) => s + e.totalHours, 0);
  const totalOT = summary.reduce((s, e) => s + e.totalOT, 0);
  const today = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  const FREQ_LABELS = { "semi-monthly": "Semi-Monthly", "weekly": "Weekly", "bi-weekly": "Bi-Weekly", "monthly": "Monthly", "custom": "Custom" };

  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Payroll Export</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #1a1a1a; margin: 0; padding: 20px; }
  h1 { font-size: 18px; margin: 0 0 4px 0; }
  .header { background: #f1f5f9; border-radius: 8px; padding: 14px 16px; margin-bottom: 20px; }
  .header-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; margin-top: 8px; }
  .header-grid span.label { font-weight: 600; }
  .emp-block { margin-bottom: 24px; break-inside: avoid; page-break-inside: avoid; }
  .emp-header { background: #f1f5f9; padding: 8px 12px; border-radius: 6px 6px 0 0; display: flex; justify-content: space-between; align-items: center; font-weight: 600; font-size: 12px; }
  .emp-header.ot { background: #fff3e0; }
  .ot-badge { background: #f97316; color: white; padding: 2px 8px; border-radius: 999px; font-size: 10px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #e2e8f0; text-align: left; padding: 5px 8px; font-size: 10px; font-weight: 600; }
  td { padding: 4px 8px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
  tr.subtotal td { background: #f1f5f9; font-weight: 600; }
  .ot-val { color: #ea580c; font-weight: 600; }
  .footer { background: #f1f5f9; border-radius: 8px; padding: 12px 16px; margin-top: 20px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; text-align: center; }
  .footer .num { font-size: 18px; font-weight: 700; }
  .footer .lbl { font-size: 10px; color: #64748b; }
  .footer .num.ot { color: #ea580c; }
  @media print { body { padding: 10px; } }
</style>
</head>
<body>
  <div class="header">
    <h1>${agencyName || "CareFlow Ops"}</h1>
    <div class="header-grid">
      <div><span class="label">Pay Period:</span> ${period.label}</div>
      <div><span class="label">Frequency:</span> ${FREQ_LABELS[frequency] || frequency}</div>
      <div><span class="label">Generated On:</span> ${today}</div>
      <div><span class="label">Generated By:</span> ${user?.full_name || user?.email || "—"}</div>
    </div>
  </div>

  ${summary.map(emp => `
    <div class="emp-block">
      <div class="emp-header ${emp.hasOT ? "ot" : ""}">
        <span>${emp.staff_name}</span>
        <span style="display:flex;align-items:center;gap:12px;">
          ${emp.hasOT ? `<span class="ot-badge">⚠ OT Detected</span>` : ""}
          <span>Total: ${fmt(emp.totalHours)}h${emp.totalOT > 0 ? ` <span class="ot-val">(${fmt(emp.totalOT)}h OT)</span>` : ""}</span>
        </span>
      </div>
      <table>
        <thead>
          <tr><th>Date</th><th>Clock In</th><th>Clock Out</th><th>Hours</th><th>Regular</th><th>OT</th><th>Status</th></tr>
        </thead>
        <tbody>
          ${[...emp.entries].sort((a, b) => a.date.localeCompare(b.date)).map(e => `
            <tr>
              <td>${e.date}</td>
              <td>${e.clock_in}</td>
              <td>${e.clock_out || "—"}</td>
              <td>${fmt(e.total_hours)}h ${e.isOT ? '<span class="ot-val">OT</span>' : ""}</td>
              <td>${fmt(e.tcRegular)}h</td>
              <td class="${e.tcOT > 0 ? "ot-val" : ""}">${e.tcOT > 0 ? fmt(e.tcOT) + "h" : "—"}</td>
              <td>${e.status}</td>
            </tr>
          `).join("")}
          <tr class="subtotal">
            <td colspan="3" style="text-align:right">Subtotal</td>
            <td>${fmt(emp.totalHours)}h</td>
            <td>${fmt(emp.totalRegular)}h</td>
            <td class="${emp.totalOT > 0 ? "ot-val" : ""}">${emp.totalOT > 0 ? fmt(emp.totalOT) + "h" : "—"}</td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  `).join("")}

  ${summary.length > 0 ? `
  <div class="footer">
    <div><div class="num">${summary.length}</div><div class="lbl">Employees</div></div>
    <div><div class="num">${summary.reduce((s, e) => s + e.entries.length, 0)}</div><div class="lbl">Total Entries</div></div>
    <div><div class="num">${fmt(totalHours)}h</div><div class="lbl">Total Hours</div></div>
    <div><div class="num ${totalOT > 0 ? "ot" : ""}">${fmt(totalOT)}h</div><div class="lbl">Total OT Hours</div></div>
  </div>
  ` : ""}
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (win) {
    win.onload = () => {
      win.print();
      URL.revokeObjectURL(url);
    };
  }
}